spring.application.name=Image_app

spring.mvc.static-path-pattern=/uploads/**
spring.web.resources.static-locations=classpath:/static/,file:uploads/

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
